/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tk.ds.ui;

import com.tk.ds.common.Snapshot;

/**
 *
 * @author kamathar
 */
public class DsUi extends javax.swing.JFrame {
	   
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JLabel accountLabel2;
    private javax.swing.JLabel accountLabel3;
    private javax.swing.JLabel accountLable1;
    private javax.swing.JPanel accountPanel1;
    private javax.swing.JPanel accountPanel2;
    private javax.swing.JPanel accountPanel3;
    private javax.swing.JTextArea infoPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton snapshotButton1;
    private javax.swing.JButton snapshotButton2;
    private javax.swing.JButton snapshotButton3;
    private javax.swing.JLabel infoLabel;
    
    private Snapshot snapshot;
    /**
     * Creates new form DsUi
     */
    public DsUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        DisplayPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoPanel = new javax.swing.JTextArea();
        ControlPanel = new javax.swing.JPanel();
        accountPanel1 = new javax.swing.JPanel();
        accountLable1 = new javax.swing.JLabel();
        snapshotButton1 = new javax.swing.JButton();
        accountPanel2 = new javax.swing.JPanel();
        accountLabel2 = new javax.swing.JLabel();
        snapshotButton2 = new javax.swing.JButton();
        accountPanel3 = new javax.swing.JPanel();
        accountLabel3 = new javax.swing.JLabel();
        snapshotButton3 = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DistributedSnapshot");
        setResizable(false);

        infoPanel.setColumns(20);
        infoPanel.setRows(5);
        jScrollPane1.setViewportView(infoPanel);

        javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
        DisplayPanel.setLayout(DisplayPanelLayout);
        DisplayPanelLayout.setHorizontalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );
        DisplayPanelLayout.setVerticalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        accountPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        accountLable1.setText("Account 1");

        snapshotButton1.setText("Snapshot");
        snapshotButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snapshotButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountPanel1Layout = new javax.swing.GroupLayout(accountPanel1);
        accountPanel1.setLayout(accountPanel1Layout);
        accountPanel1Layout.setHorizontalGroup(
            accountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanel1Layout.createSequentialGroup()
                .addComponent(accountLable1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(accountPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(snapshotButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountPanel1Layout.setVerticalGroup(
            accountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanel1Layout.createSequentialGroup()
                .addComponent(accountLable1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(snapshotButton1)
                .addGap(25, 25, 25))
        );

        accountPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        accountLabel2.setText("Account 2");

        snapshotButton2.setText("Snapshot");
        snapshotButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snapshotButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountPanel2Layout = new javax.swing.GroupLayout(accountPanel2);
        accountPanel2.setLayout(accountPanel2Layout);
        accountPanel2Layout.setHorizontalGroup(
            accountPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanel2Layout.createSequentialGroup()
                .addComponent(accountLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(accountPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(snapshotButton2)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        accountPanel2Layout.setVerticalGroup(
            accountPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanel2Layout.createSequentialGroup()
                .addComponent(accountLabel2)
                .addGap(26, 26, 26)
                .addComponent(snapshotButton2)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        accountPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        accountLabel3.setText("Account 3");

        snapshotButton3.setText("Snapshot");
        snapshotButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snapshotButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountPanel3Layout = new javax.swing.GroupLayout(accountPanel3);
        accountPanel3.setLayout(accountPanel3Layout);
        accountPanel3Layout.setHorizontalGroup(
            accountPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanel3Layout.createSequentialGroup()
                .addComponent(accountLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(snapshotButton3)
                .addGap(35, 35, 35))
        );
        accountPanel3Layout.setVerticalGroup(
            accountPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanel3Layout.createSequentialGroup()
                .addComponent(accountLabel3)
                .addGap(36, 36, 36)
                .addComponent(snapshotButton3)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accountPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(accountPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        infoLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        infoLabel.setText("Account activities");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }


    private void snapshotButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void snapshotButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void snapshotButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param snapshot 
     * @param args the command line arguments
     */
    void initUi(Snapshot snapshot) {
       this.snapshot= snapshot;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DsUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DsUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DsUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DsUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DsUi().setVisible(true);
            }
        });
    }


    
}
