/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tk.ds.ui;

import java.awt.GridLayout;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

import com.tk.ds.common.MessageMark;
import com.tk.ds.process.Sender;

/**
 *
 * @author kamathar
 */
@SuppressWarnings("serial")
public class DsUi implements UiUpdatesListner {
	private javax.swing.JFrame mainFrame;
	private javax.swing.JPanel ControlPanel;
	private javax.swing.JPanel DisplayPanel;
	private javax.swing.JLabel accountLabel2;
	private javax.swing.JLabel accountLabel3;
	private javax.swing.JLabel accountLable1;
	private javax.swing.JPanel accountPanel1;
	private javax.swing.JPanel accountPanel2;
	private javax.swing.JPanel accountPanel3;
	private javax.swing.JTextArea infoTextArea;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton snapshotButton1;
	private javax.swing.JButton snapshotButton2;
	private javax.swing.JButton snapshotButton3;
	private javax.swing.JTextField accountBalance1;
	private javax.swing.JTextField accountBalance2;
	private javax.swing.JTextField accountBalance3;
	private javax.swing.JLabel infoLabel;
	UiMessageHandler manager;

	/**
	 * Creates new form DsUi
	 */
	public DsUi(UiMessageHandler manager) {
		this.manager = manager;
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		mainFrame = new JFrame("Distributed snapshot");
		DisplayPanel = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		infoTextArea = new javax.swing.JTextArea();
		ControlPanel = new javax.swing.JPanel();
		accountPanel1 = new javax.swing.JPanel();
		accountLable1 = new javax.swing.JLabel();
		snapshotButton1 = new javax.swing.JButton();
		accountPanel2 = new javax.swing.JPanel();
		accountLabel2 = new javax.swing.JLabel();
		snapshotButton2 = new javax.swing.JButton();
		accountPanel3 = new javax.swing.JPanel();
		accountLabel3 = new javax.swing.JLabel();
		snapshotButton3 = new javax.swing.JButton();
		infoLabel = new javax.swing.JLabel();
		accountBalance1 = new JTextField("0");
		accountBalance1.setEditable(false);
		accountBalance2 = new JTextField("0");
		accountBalance2.setEditable(false);
		accountBalance3 = new JTextField("0");
		accountBalance3.setEditable(false);

		manager.addListners(this);

		mainFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		mainFrame.setResizable(false);

		infoTextArea.setColumns(20);
		infoTextArea.setRows(5);
		jScrollPane1.setViewportView(infoTextArea);

		javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
		DisplayPanel.setLayout(DisplayPanelLayout);
		DisplayPanelLayout
				.setHorizontalGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(DisplayPanelLayout.createSequentialGroup().addContainerGap()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
								.addContainerGap()));
		DisplayPanelLayout.setVerticalGroup(DisplayPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(DisplayPanelLayout
						.createSequentialGroup().addGap(0, 0, 0).addComponent(jScrollPane1).addContainerGap()));

		accountPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		accountLable1.setText("Account 1");

		snapshotButton1.setText("Snapshot");
		snapshotButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				snapshotButton1ActionPerformed(evt);
			}
		});

		GridLayout accountPanel1Layout = new GridLayout(3, 1);

		accountPanel1.setLayout(accountPanel1Layout);
		accountPanel1.add(accountLable1);
		GridLayout accBalanceLayout1 = new GridLayout(1, 2);
		JPanel balancePanle1 = new JPanel(accBalanceLayout1);
		balancePanle1.add(new JLabel("Account balance ($)"));
		balancePanle1.add(accountBalance1);
		accountPanel1.add(balancePanle1);
		accountPanel1.add(snapshotButton1);

		accountPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		accountLabel2.setText("Account 2");

		snapshotButton2.setText("Snapshot");
		snapshotButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				snapshotButton2ActionPerformed(evt);
			}
		});

		GridLayout accountPanel2Layout = new GridLayout(3, 1);

		accountPanel2.setLayout(accountPanel2Layout);
		accountPanel2.add(accountLabel2);
		GridLayout accBalanceLayout2 = new GridLayout(1, 2);
		JPanel balancePanle2 = new JPanel(accBalanceLayout2);
		balancePanle2.add(new JLabel("Account balance ($)"));
		balancePanle2.add(accountBalance2);
		accountPanel2.add(balancePanle2);
		accountPanel2.add(snapshotButton2);

		accountPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		accountLabel3.setText("Account 3");

		snapshotButton3.setText("Snapshot");
		snapshotButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				snapshotButton3ActionPerformed(evt);
			}
		});

		GridLayout accountPanel3Layout = new GridLayout(3, 1);

		accountPanel3.setLayout(accountPanel3Layout);
		accountPanel3.add(accountLabel3);
		GridLayout accBalanceLayout3 = new GridLayout(1, 2);
		JPanel balancePanle3 = new JPanel(accBalanceLayout3);
		balancePanle3.add(new JLabel("Account balance ($)"));
		balancePanle3.add(accountBalance3);
		accountPanel3.add(balancePanle3);
		accountPanel3.add(snapshotButton3);

		javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
		ControlPanel.setLayout(ControlPanelLayout);
		ControlPanelLayout.setHorizontalGroup(ControlPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(ControlPanelLayout.createSequentialGroup().addContainerGap()
						.addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(accountPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(accountPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(accountPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));
		ControlPanelLayout
				.setVerticalGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(ControlPanelLayout.createSequentialGroup().addContainerGap()
								.addComponent(accountPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(accountPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(18, 18, 18)
						.addComponent(accountPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		infoLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
		infoLabel.setText("Account activities");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(mainFrame.getContentPane());
		mainFrame.getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(DisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(25, 25, 25))
				.addGroup(layout.createSequentialGroup().addGap(24, 24, 24)
						.addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(infoLabel).addGap(3, 3, 3)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(DisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));

		mainFrame.setVisible(true);
		mainFrame.pack();
	}

	private void snapshotButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		sendMarkMessage(1);
	}

	private void snapshotButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		sendMarkMessage(2);
	}

	private void snapshotButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		sendMarkMessage(3);
	}

	/**
	 * Send MARK message to a process
	 * 
	 * @param process
	 */
	void sendMarkMessage(int process) {
		// Build and send a mark message to corresponding process
		Sender.sendToProcess(new MessageMark(0, process));
	}

	/**
	 * @param snapshot
	 * @param args
	 *            the command line arguments
	 */
	void initUi() {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DsUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DsUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DsUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DsUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the form */
		// java.awt.EventQueue.invokeLater(new Runnable() {
		// public void run() {
		// new DsUi().mainFrame.setVisible(true);
		// }
		// });
	}

	@Override
	public void updateAccountBalance(int accountBalance, int accountNumber) {
		if (accountNumber == 1)
			accountBalance1.setText(accountBalance + "");
		else if (accountNumber == 2)
			accountBalance2.setText(accountBalance + "");
		else if (accountNumber == 3)
			accountBalance3.setText(accountBalance + "");
	}

	@Override
	public void updateInfo(String info) {
		infoTextArea.append("\n" + info);
		mainFrame.repaint();
		mainFrame.revalidate();
	}
}
